SET SERVEROUTPUT ON;
DROP TABLE BOOK;
CREATE TABLE BOOK (
    ACCNO NUMBER(4),
    TITLE VARCHAR2(100),
    AUTHOR VARCHAR2(20),
    PUBLISHER VARCHAR2(20),
    EDITION VARCHAR2(10),
    NO_COPY NUMBER(10)
);


INSERT INTO BOOK (ACCNO, TITLE, AUTHOR, PUBLISHER, EDITION, NO_COPY)
VALUES (1001, 'Moby Dick', 'Herman Melville', 'Harper & Brothers', 'First', 3);

INSERT INTO BOOK (ACCNO, TITLE, AUTHOR, PUBLISHER, EDITION, NO_COPY)
VALUES (1002, 'War and Peace', 'Leo Tolstoy', 'The Russian Messenger', 'Second', 4);

INSERT INTO BOOK (ACCNO, TITLE, AUTHOR, PUBLISHER, EDITION, NO_COPY)
VALUES (1003, 'Crime and Punishment', 'Fyodor Dostoevsky', 'The Russian Messenger', 'First', 6);

INSERT INTO BOOK (ACCNO, TITLE, AUTHOR, PUBLISHER, EDITION, NO_COPY)
VALUES (1004, 'The Odyssey', 'Homer', 'Penguin Classics', 'Revised', 8);

INSERT INTO BOOK (ACCNO, TITLE, AUTHOR, PUBLISHER, EDITION, NO_COPY)
VALUES (1005, 'The Iliad', 'Homer', 'Penguin Classics', 'Revised', 7);

CREATE OR REPLACE TRIGGER TOTAL_TUPLE
AFTER INSERT OR DELETE OR UPDATE ON BOOK
DECLARE
    NO NUMBER;
BEGIN
    SELECT COUNT(*) INTO NO FROM BOOK;

    DBMS_OUTPUT.PUT_LINE('NO OF TUPLE: ' || NO);
END;
/

INSERT INTO BOOK (ACCNO, TITLE, AUTHOR, PUBLISHER, EDITION, NO_COPY)
VALUES (1006, 'The Hobbit', 'J.R.R. Tolkien', 'George Allen & Unwin', 'First', 5);